#----------- <Permisos> -----------
#
aire:
  - bending.ability.AirBlast
  - bending.ability.AirBurst
  - bending.ability.AirScooter
  - bending.ability.AirShield
  - bending.ability.AirSpout
  - bending.ability.AirSuction
  - bending.ability.AirSwipe
  - bending.ability.Suffocate
  - bending.ability.Tornado
  - bending.ability.AirCombo
  - bending.air.passive
  - bending.air.flight
agua:
  - bending.ability.Bloodbending
  - bending.ability.HealingWaters
  - bending.ability.IceBlast
  - bending.ability.IceSpike
  - bending.ability.OctopusForm
  - bending.ability.PhaseChange
  - bending.ability.Surge
  - bending.ability.Torrent
  - bending.ability.WaterBubble
  - bending.ability.WaterManipulation
  - bending.ability.WaterSpout
  - bending.ability.WaterSpout
  - bending.ability.WaterCombo
  - bending.water.plantbending
  - bending.water.passive
  - bending.water.icebending
  - bending.water.healing
  - bending.ability.WaterArms
  - bending.ability.WaterArms
  - bending.ability.WaterArms
  - bending.ability.WaterArms
  - bending.ability.WaterArms
  - bending.ability.WaterArms
  - bending.ability.WaterArms
  - bending.ability.Bottlebending
tierra:
  - bending.ability.Catapult
  - bending.ability.Collapse
  - bending.ability.EarthArmor
  - bending.ability.EarthBlast
  - bending.ability.EarthGrab
  - bending.ability.EarthTunnel
  - bending.ability.RaiseEarth
  - bending.ability.Shockwave
  - bending.ability.Tremorsense
  - bending.ability.Extraction
  - bending.ability.MetalClips
  - bending.earth.passive
  - bending.earth.metalbending
  - bending.earth.lavabending
  - bending.earth.sandbending
  - bending.ability.LavaSurge
  - bending.ability.LavaFlow
  - bending.ability.EarthSmash
  - bending.ability.SandSpout
  - bending.ability.EarthCombo
fuego:
  - bending.ability.Blaze
  - bending.ability.FireBlast
  - bending.ability.FireBurst
  - bending.ability.FireJet
  - bending.ability.FireShield
  - bending.ability.HeatControl
  - bending.ability.Illumination
  - bending.ability.Lightning
  - bending.ability.WallOfFire
  - bending.ability.Combustion
  - bending.ability.FireManipulation
  - bending.ability.FireCombo
  - bending.fire.passive
  - bending.fire.lightningbending
  - bending.fire.combustionbending

#----------- <Players> ----------

FulanoTestero:
  cd: 0
  debug: false
  contador: 0
  elemento: nada
  fragmentos: 0
