#----------- <Permisos> -----------
#
aire:
  - atla.ability.AirAgility
  - atla.ability.AirBlast
  - atla.ability.AirBurst
  - atla.ability.AirScooter
  - atla.ability.AirShield
  - atla.ability.AirSpout
  - atla.ability.AirStream
  - atla.ability.AirSuction
  - atla.ability.AirSweep
  - atla.ability.GracefulDescent
  - atla.ability.Suffocate
  - atla.ability.Tornado
  - atla.ability.Twister
agua:
  - nada
tierra:
  - atla.ability.Catapult
  - atla.ability.Collapse
  - atla.ability.EarthArmor
  - atla.ability.EarthSmash
  - atla.ability.EarthTunnel
  - atla.ability.RaiseEarth
  - atla.ability.Shockwave
  - atla.ability.DensityShift
fuego:
  - atla.ability.Combustion
  - atla.ability.FireBlast
  - atla.ability.FireBlastCharged
  - atla.ability.FireBurst
  - atla.ability.FireJet
  - atla.ability.FireShield
  - atla.ability.HeatControl
  - atla.ability.Lightning
  - atla.ability.WallOfFire
  - atla.ability.FireKick
  - atla.ability.FireSpin
  - atla.ability.FireWheel
  - atla.ability.JetBlast
  - atla.ability.JetBlaze

#----------- <Players> ----------

FulanoTestero:
  cd: 0
  debug: false
  contador: 0
  elemento: nada
  fragmentos: 0
